/* --COPYRIGHT--,BSD
 * Copyright (c) 2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * --/COPYRIGHT--*/


// Generated by Captivate Design Center v1_83_00_08 on Thu Mar 05 13:18:27 ICT 2026


//*****************************************************************************
// CAPT_UserConfig.c
//
// \version 1.83.00.05
// Released on May 15, 2020
//
//*****************************************************************************

//*****************************************************************************
//
// NOTE: This is an automatically generated source code file!  The Captivate
// Design Center generates the User Configuration file automatically based
// upon the sensor layout that was created.
//
// Changes to this file will be OVERWRITTEN if a you select
// "Update Existing Project" under "Generate Source Code" in the Design Center.
//
// To avoid interference with the code generation process, keep ALL application
// code external to this file.
//
//*****************************************************************************

#include "CAPT_UserConfig.h"

//*****************************************************************************
//
//! Captivate Element Definitions
//! All elements in this application are defined below.
//! Each element has 3 components:
//!  1) a raw count array (One index per freq. scanned) (uint16_t)
//!  2) a tuning array (One index per freq. scanned) (tCaptivateElementTuning)
//!  3) a element structure (tElement)
//
//*****************************************************************************
// Sensor: BTN01, Element: E00
uint16_t BTN01_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN01_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN01_E00 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN01_E00_RawCnts,
    .pTuning = BTN01_E00_Tuning,
};

// Sensor: BTN01, Element: E01
uint16_t BTN01_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN01_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN01_E01 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN01_E01_RawCnts,
    .pTuning = BTN01_E01_Tuning,
};

// Sensor: BTN01, Element: E02
uint16_t BTN01_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN01_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN01_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 2,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN01_E02_RawCnts,
    .pTuning = BTN01_E02_Tuning,
};

// Sensor: BTN01, Element: E03
uint16_t BTN01_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN01_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN01_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 3,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN01_E03_RawCnts,
    .pTuning = BTN01_E03_Tuning,
};

// Sensor: BTN02, Element: E00
uint16_t BTN02_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E00 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 0,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E00_RawCnts,
    .pTuning = BTN02_E00_Tuning,
};

// Sensor: BTN02, Element: E01
uint16_t BTN02_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E01 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 0,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E01_RawCnts,
    .pTuning = BTN02_E01_Tuning,
};

// Sensor: BTN02, Element: E02
uint16_t BTN02_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E02 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E02_RawCnts,
    .pTuning = BTN02_E02_Tuning,
};

// Sensor: BTN02, Element: E03
uint16_t BTN02_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E03 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 0,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E03_RawCnts,
    .pTuning = BTN02_E03_Tuning,
};

// Sensor: BTN02, Element: E04
uint16_t BTN02_E04_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E04_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E04 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 1,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E04_RawCnts,
    .pTuning = BTN02_E04_Tuning,
};

// Sensor: BTN02, Element: E05
uint16_t BTN02_E05_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E05_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E05 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 1,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E05_RawCnts,
    .pTuning = BTN02_E05_Tuning,
};

// Sensor: BTN02, Element: E06
uint16_t BTN02_E06_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E06_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E06 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E06_RawCnts,
    .pTuning = BTN02_E06_Tuning,
};

// Sensor: BTN02, Element: E07
uint16_t BTN02_E07_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E07_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E07 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 1,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E07_RawCnts,
    .pTuning = BTN02_E07_Tuning,
};

// Sensor: BTN02, Element: E08
uint16_t BTN02_E08_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E08_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E08 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E08_RawCnts,
    .pTuning = BTN02_E08_Tuning,
};

// Sensor: BTN02, Element: E09
uint16_t BTN02_E09_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN02_E09_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN02_E09 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN02_E09_RawCnts,
    .pTuning = BTN02_E09_Tuning,
};

// Sensor: BTN03, Element: E00
uint16_t BTN03_E00_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E00_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E00 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E00_RawCnts,
    .pTuning = BTN03_E00_Tuning,
};

// Sensor: BTN03, Element: E01
uint16_t BTN03_E01_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E01_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E01 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 2,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E01_RawCnts,
    .pTuning = BTN03_E01_Tuning,
};

// Sensor: BTN03, Element: E02
uint16_t BTN03_E02_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E02_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E02 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 3,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E02_RawCnts,
    .pTuning = BTN03_E02_Tuning,
};

// Sensor: BTN03, Element: E03
uint16_t BTN03_E03_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E03_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E03 =
{
    .ui8TxPin = 1,
    .ui8TxBlock = 3,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E03_RawCnts,
    .pTuning = BTN03_E03_Tuning,
};

// Sensor: BTN03, Element: E04
uint16_t BTN03_E04_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E04_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E04 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 0,
    .ui8RxBlock = 0,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E04_RawCnts,
    .pTuning = BTN03_E04_Tuning,
};

// Sensor: BTN03, Element: E05
uint16_t BTN03_E05_RawCnts[CAPT_MUTUAL_FREQ_CNT];
tCaptivateElementTuning BTN03_E05_Tuning[CAPT_MUTUAL_FREQ_CNT];
tElement BTN03_E05 =
{
    .ui8TxPin = 2,
    .ui8TxBlock = 3,
    .ui8RxPin = 0,
    .ui8RxBlock = 1,
    .ui8TouchThreshold = 110,
    .pRawCount = BTN03_E05_RawCnts,
    .pTuning = BTN03_E05_Tuning,
};


//*****************************************************************************
//
//! Captivate Time Cycle Definitions
//! All time cycles in this application are defined below.  Time cycles are
//! groups of elements that are measured together in parallel in one time slot.
//! Each cycle has 2 components:
//!  1) an element pointer array to the member elements (tElement*)
//!  2) a cycle structure (tCycle)
//
//*****************************************************************************
// Time Cycle: BTN01_C00
tElement* BTN01_C00_Elements[2] =
{
    &BTN01_E00,
    &BTN01_E01,
};
tCycle BTN01_C00 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN01_C00_Elements,
};

// Time Cycle: BTN01_C01
tElement* BTN01_C01_Elements[2] =
{
    &BTN01_E02,
    &BTN01_E03,
};
tCycle BTN01_C01 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN01_C01_Elements,
};

// Time Cycle: BTN02_C00
tElement* BTN02_C00_Elements[2] =
{
    &BTN02_E00,
    &BTN02_E01,
};
tCycle BTN02_C00 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN02_C00_Elements,
};

// Time Cycle: BTN02_C01
tElement* BTN02_C01_Elements[2] =
{
    &BTN02_E02,
    &BTN02_E03,
};
tCycle BTN02_C01 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN02_C01_Elements,
};

// Time Cycle: BTN02_C02
tElement* BTN02_C02_Elements[2] =
{
    &BTN02_E04,
    &BTN02_E05,
};
tCycle BTN02_C02 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN02_C02_Elements,
};

// Time Cycle: BTN02_C03
tElement* BTN02_C03_Elements[2] =
{
    &BTN02_E06,
    &BTN02_E07,
};
tCycle BTN02_C03 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN02_C03_Elements,
};

// Time Cycle: BTN02_C04
tElement* BTN02_C04_Elements[2] =
{
    &BTN02_E08,
    &BTN02_E09,
};
tCycle BTN02_C04 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN02_C04_Elements,
};

// Time Cycle: BTN03_C00
tElement* BTN03_C00_Elements[2] =
{
    &BTN03_E00,
    &BTN03_E01,
};
tCycle BTN03_C00 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN03_C00_Elements,
};

// Time Cycle: BTN03_C01
tElement* BTN03_C01_Elements[2] =
{
    &BTN03_E02,
    &BTN03_E03,
};
tCycle BTN03_C01 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN03_C01_Elements,
};

// Time Cycle: BTN03_C02
tElement* BTN03_C02_Elements[2] =
{
    &BTN03_E04,
    &BTN03_E05,
};
tCycle BTN03_C02 =
{
    .ui8NrOfElements = 2,
    .pElements = BTN03_C02_Elements,
};


//*****************************************************************************
//
//! Captivate Sensor Definitions
//! All sensors in this application are defined below.  Sensors are
//! groups of time cycles that utilize raw measurement data to create an
//! abstract sensor type, such as a button, slider, wheel, or prox sensor.
//! Each sensor has 3 components:
//!  1) a cycle pointer array to the member time cycles (tCycle*)
//!  2) a sensor-specific parameter structure (tGenericSensorParams)
//!  3) a sensor structure (tSensor)
//
//*****************************************************************************
//Sensor: BTN01
const tCycle* BTN01_Cycles[2] =
{
    &BTN01_C00,
    &BTN01_C01,
};

tButtonSensorParams BTN01_Params;
tSensor BTN01 =
{
    // Basic Properties
    .TypeOfSensor = eButtonGroup,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 2,
    .pCycle = BTN01_Cycles,
    .pSensorParams = (tGenericSensorParams*)&BTN01_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 1,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 100,
    .ui16NegativeTouchThreshold = 1000,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 0,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 3,
    .TouchDbThreshold.DbOut = 3,
    .bCountFilterEnable = true,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: BTN02
const tCycle* BTN02_Cycles[5] =
{
    &BTN02_C00,
    &BTN02_C01,
    &BTN02_C02,
    &BTN02_C03,
    &BTN02_C04,
};

tButtonSensorParams BTN02_Params;
tSensor BTN02 =
{
    // Basic Properties
    .TypeOfSensor = eButtonGroup,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 5,
    .pCycle = BTN02_Cycles,
    .pSensorParams = (tGenericSensorParams*)&BTN02_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 400,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 1,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 110,
    .ui16NegativeTouchThreshold = 1000,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = true,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};

//Sensor: BTN03
const tCycle* BTN03_Cycles[3] =
{
    &BTN03_C00,
    &BTN03_C01,
    &BTN03_C02,
};

tButtonSensorParams BTN03_Params;
tSensor BTN03 =
{
    // Basic Properties
    .TypeOfSensor = eButtonGroup,
    .SensingMethod = eProjected,
    .DirectionOfInterest = eDOIUp,
    .pvCallback = NULL,
    .ui8NrOfCycles = 3,
    .pCycle = BTN03_Cycles,
    .pSensorParams = (tGenericSensorParams*)&BTN03_Params,
    // Conversion Control Parameters
    .ui16ConversionCount = 500,
    .ui16ConversionGain = 100,
    .ui8FreqDiv = 1,
    .ui8ChargeLength = 0,
    .ui8TransferLength = 0,
    .bModEnable = false,
    .ui8BiasControl = 3,
    .bCsDischarge = true,
    .bLpmControl = false,
    .ui8InputSyncControl = 0,
    .bTimerSyncControl = false,
    .bIdleState = true,
    // Tuning  Parameters
    .ui16ProxThreshold = 110,
    .ui16NegativeTouchThreshold = 1000,
    .ui16ErrorThreshold = 8191,
    .ui16TimeoutThreshold = 65535,
    .ProxDbThreshold.DbIn = 1,
    .ProxDbThreshold.DbOut = 0,
    .TouchDbThreshold.DbIn = 1,
    .TouchDbThreshold.DbOut = 0,
    .bCountFilterEnable = true,
    .ui8CntBeta = 1,
    .bSensorHalt = false,
    .bPTSensorHalt = true,
    .bPTElementHalt = true,
    .ui8LTABeta = 7,
    .bReCalibrateEnable = true,
};


#if (CAPT_CONDUCTED_NOISE_IMMUNITY_ENABLE==true)
//*****************************************************************************
//
//! \var g_EMCConfig
//! This structure stores the EMC configuration for this application.
//
//*****************************************************************************
const tEMCConfig g_EMCConfig =
{
	// Conversion Style
	.selfModeConversionStyle = CAPT_SELF_MODE_CONVERSION_STYLE,
	.projModeConversionStyle = CAPT_PROJ_MODE_CONVERSION_STYLE,
	
	// Oversampling Style
	.selfModeOversamplingStyle = CAPT_SELF_MODE_OVERSAMPLING_STYLE,
	.projModeOversamplingStyle = CAPT_PROJ_MODE_OVERSAMPLING_STYLE,
	
	// Jitter Filter Enable
	.bJitterFilterEnable = true,
	
	// Noise Thresholds and Calibration Noise Limits
	.ui8NoiseThreshold = CAPT_NOISE_THRESHOLD,
	.ui16CalibrationNoiseLimit = CAPT_CALIBRATION_NOISE_LIMIT,
	.ui8CalibrationTestSampleSize = 8,
		
	// Dynamic Threshold Adjustment Parameters
	.bEnableDynamicThresholdAdjustment = CAPT_DYNAMIC_THRESHOLD_ADJUSTMENT,
	.ui8MaxRelThreshAdj = 76,
	.ui8NoiseLevelFilterEntryThresh = 40,
	.ui8NoiseLevelFilterExitThresh = 0,
	.ui8NoiseLevelFilterDown = 6,
	.ui8NoiseLevelFilterUp = 1,
	.coeffA = _IQ31(0.0065),
	.coeffB = _IQ31(0.050)
};
#endif

//*****************************************************************************
//
//! \var g_pCaptivateSensorArray
//! This array allows for indexed access to any
//! sensor in the configuration.
//
//*****************************************************************************
tSensor* g_pCaptivateSensorArray[CAPT_SENSOR_COUNT] =
{
    &BTN01,
    &BTN02,
    &BTN03,
};


//*****************************************************************************
//
//! \var g_uiApp
//! This structure stores the global settings for this application.
//
//*****************************************************************************
tCaptivateApplication g_uiApp =
{
    .state = eUIActive,
	.pSensorList = &g_pCaptivateSensorArray[0],
    .ui8NrOfSensors = CAPT_SENSOR_COUNT,
    .ui8AppLPM = CAPT_LOW_POWER_MODE,
    .bElementDataTxEnable = true,
    .bSensorDataTxEnable = true,
    .ui16ActiveModeScanPeriod = 33,
    .ui16WakeOnProxModeScanPeriod = 100,
    .ui16InactivityTimeout = 32,
    .ui8WakeupInterval = 5,
};
